### ISSUE TITLE
Ready method example could be improved

### ISSUE THREAD

**Issue by robdodson** [Polymer/docs#1005]
https://www.polymer-project.org/0.8/docs/devguide/registering-elements.html#ready-method

"Implement ready when it’s necessary to manipulate an element’s local DOM when the element is constructed."

```
ready: function() {
  this.$.ajax.go();
}
```

The above example doesn't really manipulate the DOM (it calls a method on something in the DOM) but the part that caught me was that automatic node finding has not been explained in this part of the 0.8 docs so if someone was reading this as a totally new user to Polymer they might not know what the $ means.

Suggestion: maybe have the example do something like

```
ready: function() {
  this.querySelector('.some-child').setAttribute('aria-hidden', 'true')
}
```

**Comment by arthurevans** [comment]
Hm. That's an interesting one, because anything that really depends on `ready` is going to involve local DOM.

For example, the `querySelector` should be:

    Polymer.dom(this.root).querySelector('.some-child') ...

But the current example bundles together `$` and `core-ajax`, which is needlessly complex... Maybe we can simplify a bit and add a brief explanation of `$` with a cross-reference to the doc for automatic node finding. 

    ready: function() {
      this.$.container.innerHTML = "<b>Hi!</b>";
    }

Most examples I can think of are a little synthetic (like innerHTML, something we'd usually prefer to do in the template, either statically or with data binding).

**Comment by robdodson** [comment]
Maybe just explaining $ with a little link out to automatic node finding would be good.

`this.$.header.textContent = 'hello world!'` or something?
