### ISSUE TITLE
Data binding helper elements needs more explanation

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/docs#1115]
> Note: The model property is not added for event listeners registered imperatively (using addEventListener), or listeners added to one of the <dom-repeat> template’s parent nodes. In these cases, you can use the <dom-repeat> modelForElement method to retrieve the model data that generated a given element. (There are also corresponding itemForElement and indexForElement methods.)

There are no details of using `modelForElement`, `itemForElement` and `indexForElement`. Meaning at least call syntax.

```
<array-selector id="selector" items="{{employees}}" selected="{{selected}}" multi toggle></array-selector>
```

Besides `array-selector` is really confusing for me, `toggle` attribute seems to have special meaning, but not mentioned anywhere.

**Comment by MonsterElf** [comment]
having the same thoughts..

**Comment by arthurevans** [comment]
The confusion with `array-selector`'s `toggle` property is the result of a bug, fixed in master but not yet released:

https://github.com/Polymer/polymer/issues/1810

The bug means that multi-selection doesn't work unless `toggle` is also specified. Single selection works fine.

Docs need to be improved. The short summary for array-selector is that it maintains an association between two _paths_ in the data binding system -- the path for the array, and the path for the selected item or items.

For example, consider a single select scenario. If you maintain the section yourself, you might use the following code in the context of an element:

    this.selected = this.array[0];

The object at `array[0]` can now be reached by two paths, `selected` and `array.0`. If you modify one of them:

    this.set('selected.name', newName);

Change notifications are sent for the path `selected.name`, but _not_ for the path `array.0.name`, so data bindings, observers, and computed properties that reference `array` are not updated.

Using `array-selector` to maintains the association between the two paths -- `selected` and `array.0` -- such that changes are propagated both ways. Moreover, `array-selector` needs to correctly handle the case where a new item is inserted at the front of the array. In this case, `selected` hasn't changed, but it now corresponds to `array.1` instead of `array.0`.

As for the *forElement methods, they all take the target element as an argument, so you can use `modelForElement` like this inside an event handler:

    this.$.domRepeat.modelForElement(event.target).set('item.checked', true);

You can find more information in the [API reference](http://polymer.github.io/polymer/) (select "dom-repeat" from the pulldown menu in the top left).

Hope that helps.

**Comment by pensierinmusica** [comment]
I agree with @nazar-pc, docs for `array-selector` and `*forElements` could be more descriptive. Also in general it wouldn't be bad to have a little "demo" section like often i sthe case in jQuery docs and in the Polymer Elements Catalog. In the meantime, thanks @arthurevans for the details above.

**Comment by katejeffreys** [comment]
To help me manage the issues in the docs repo, I will close this issue in 7 days. If you need it to stay open for some reason, please comment to that effect within 7 days.

**Comment by nazar-pc** [comment]
It was not fixed in more than 2 years, don't think there is anything left to be done here.

**Comment by katejeffreys** [comment]
Some explanation: The issues are unmanageable at the moment, which means that having them left open does not give meaningful or actionable input into the workflow. 

Closing old ones will hopefully mean that raising an issue is a meaningful input into the docs repo workflow rather than just the 120th "issue" in a pile of stuff that will never get done.

**Comment by arthurevans** [comment]
We've made some improvements over the years, including adding a lot more conceptual information about data binding paths, a section on binding to array items, and some more detail.

Some low-hanging fruit here: the references to modelForElement, itemForElement, etc., should be linked to the API reference.
