### ISSUE TITLE
Update samples to place <script> tags inside <dom-module> 

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1124]
_From @yutori on June 1, 2015 6:47_

In [Migration guide](https://www.polymer-project.org/1.0/docs/migration.html), I found `<script />` are defined outside of `<dom-module />`. We might as well move `<script />` to outside of `<dom-module />` in README.md.

_Copied from original issue: Polymer/polymer#1700_

**Comment by arthurevans** [comment]
_From @kevinpschaaf on June 2, 2015 21:51_

We are encouraging putting `<script>` inside the `<dom-module>` now for readability.  Either way works, and there may be a mix of examples using both syntax, so we'll try and clean that up.

@arthurevans could you do a sweep and make sure the docs are consistent in this respect?  Thanks.

**Comment by arthurevans** [comment]
_From @IntranetFactory on June 2, 2015 21:54_

When script is now again inside dom-module would it then be possible to get rid of the is: property where the dom-module name needs to be repeated? It seems that I frequently forget to change one of them when I copy and rename a component. But maybe it's just me.

**Comment by arthurevans** [comment]
I know the team liked not having to repeat the tag name in 0.5. However, it also caused some issues with vulcanize.

Not sure if support for this ("DRY element declarations") is on the roadmap -- @sorvell @azakus? Maybe you can comment.

**Comment by sorvell** [comment]
Yes, it's on the roadmap.

**Comment by askibinski** [comment]
Found an inconsistency in the 1.0 docs [here](https://www.polymer-project.org/1.0/docs/devguide/styling.html#external-stylesheets), where it is placed inside dom-element, opposed to outside which is mentioned in the migration guide.

If either way is okay, but you are encouraging to place tag inside the element (as mentioned above) that should be changed/mentioned in the migration guide IMO, otherwise things get confusing...

**Comment by arthurevans** [comment]
Fixed in #1176.
