### ISSUE TITLE
Please address replacements for :host-context in "Styling local DOM"

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#1170]
https://github.com/Polymer/polymer/blob/master/src/lib/style-transformer.html#L39 says `:host-context` is "NOT SUPPORTED", but https://www.polymer-project.org/1.0/docs/devguide/styling.html just ignores it.

It's possible to replace it with global style rules like `* /deep/ .contextclass the-element::shadow more selectors`, but you've said you're trying to move away from `/deep/` and `::shadow`, so that's probably not the replacement you have in mind.

**Comment by ebidel** [comment]
Hmm, host-context is a feature of native SD. @sorvell will `host-context` be supported eventually?

**Comment by arthurevans** [comment]
Note: testing out a new issue label for "dunno, let's ask the engineer."

**Comment by ericatha** [comment]
Any idea if this will be supported or not? I think it's the last missing piece in my migration from 0.5 to 1.0 and I don't want to rewrite a ton of styles if it will be added soon.

Also, since it isn't mentioned and kind of related...
in the following code:

**:host([dark]), :host-context([dark]) {..styles..}**

**:host([dark])** will not be styled if **:host-context([dark])** is set, but seems to work if host-context is preceded with :host, like so...

**:host([dark]), :host:host-context([dark]) {..styles..}**

**Comment by arthurevans** [comment]
This has been fixed in core, doesn't need a doc fix.
