### ISSUE TITLE
[1.0] https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#1208]
https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes

Fine, so I replaced all of the layout stuff like this `@apply(--layout-vertical);` in a new created css class in my code just to find out that in your example code you do it like this?

https://elements.polymer-project.org/elements/paper-header-panel

`class="fullbleed layout vertical"`

**Comment by arthurevans** [comment]
I think the example code in the paper-header-panel instance predates the latest version of `iron-flex-layout`. This area has been under active development to find the best patterns to use.

As currently written, the layout _classes_ rely on the `/deep/` combinator, which is slated to be removed from the shadow DOM spec. So they'll work fine for now, but if you rely on the current behavior, you may need to rewrite your elements at some point.

The custom layout properties should continue to work, which is why the migration guide recommends them.

There may be another possibility on the horizon, a stylesheet for layout classes that _don't_ use `/deep/` or `::shadow`. You'd have to import those locally to any element that used them, but you could use them as written above.

So layout properties are safe, layout classes work but may not be future proof, and I'm not going to update the documentation until the engineers swear a blood oath that they're done changing this.  

@sjmiles @frankiefu @cdata

**Comment by gertcuykens** [comment]
Ok thanks for the explanation, going to stick with `@apply()`  :)

**Comment by cdata** [comment]
Thanks for the explanation @arthurevans . This recommendation seems reasonable to me.

**Comment by dman777** [comment]
I'm not familar with `/deep/`.... from what I understand in reading this...the current `class='flex'` in  ` <paper-header-panel class="flex">` will not work in future versions?

**Comment by gertcuykens** [comment]
Something like this I think.
```css
.myelement {
 @apply(--flex)
}
```

**Comment by arthurevans** [comment]
Both class and mixin style are now documented here:

https://elements.polymer-project.org/guides/flex-layout
