### ISSUE TITLE
Polymer documentation is unvulcanize and slow

### ISSUE THREAD

**Issue by hinoka** [Polymer/docs#1257]
The polymer documentation appears to be unvulcanized and takes 800ms+ to load on a Mac Pro.

I don't think this is exactly a demonstration of Polymer being fast.

![screen shot 2015-07-14 at 2 22 09 pm](https://cloud.githubusercontent.com/assets/13121894/8685487/c4523aba-2a33-11e5-95ef-c80dcb5af25d.png)

**Comment by robdodson** [comment]
The docs are currently vulcanized, we're just not vulcanizing everything. While there's always room for improvement, loading <1s is perfectly fine. It meets the 1000/100/6 (aka RAIL) performance model (https://docs.google.com/document/d/1bYMyE6NdiAupuwl7pWQfB-vOZBPSsXCv57hljLDMV8E/edit)

**Comment by ebidel** [comment]
<1s for page load is quite reasonable for any site. From your network capture, you can see that the elements are indeed vulcanized (elements.vulcanized.html). However, we don't crush the entire page together because the site is a SPA and needs to load a "shell", shared resources across pages.

The other thing to note is that it's built in Polymer 0.5, although that shouldn't matter a great deal here since you're in chrome and this page is simple.
