### ISSUE TITLE
Tooltip demo returns 404 error

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1294]
_From @mschwart on August 5, 2015 23:53_

Steps:
1. Go to https://www.polymer-project.org/0.5/docs/elements/core-tooltip.html
2. Click on Demo button

Expected: show demo screen
Result:
```
Error: Not Found

The requested URL /0.5/components/core-tooltip/demo.html was not found on this server.
```

_Copied from original issue: Polymer/polymer#2216_

**Comment by ebidel** [comment]
The demo should be coming down with bower. It's not blocked in bower.json:
https://github.com/Polymer/core-tooltip/blob/master/bower.json

@arthurevans any ideas what's happening when you deploy?

**Comment by arthurevans** [comment]
The problem is that the 0.5 docs expect the demo to be in demo.html, and someone moved the demo to `demo/index.html`:

https://github.com/Polymer/core-tooltip/commit/764dd996528ea44e17e79f644b6993312937eaef

This change also broke all of the import paths in the demo, so it doesn't work if you request the new path, either:

https://www.polymer-project.org/0.5/components/core-tooltip/demo/index.html

So this bug is actually with the core-tooltip repo.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/core-tooltip#36
