### ISSUE TITLE
example doesn't match description

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#1303]
https://www.polymer-project.org/1.0/docs/migration.html#property-name-to-attribute-name-mapping

```
In 0.5, Polymer attempted to map attribute names to corresponding properties. For example, the attribute
foobar would map to the property fooBar if it was defined on the element. Polymer does not do this
anymore — attribute to property mappings are set up on the element at registration time based on the
rules described above.
```

The above is followed with a `before` example that uses an attribute called `fooBar`, not `foobar` as described. Specifically, this part `attributes="fooBar"`.
It's just a small thing that introduces a 'note' of confusion in the mind of the reader - although I may possibly have misunderstood.

Please consider changing the `before` example to use an attribute named `foobar`.

**Comment by arthurevans** [comment]
So, I think the confusion here is that in Polymer 0.5, the name you listed in the `attributes` attribute was ... the property name. 

It's significant because in the old Polymer, that would match the _attribute_ name `foobar` (case insensitive), so `fooBar` or `FOOBAR` would work. In the new Polymer, we're more precise and we require dashes to match camel-case properties (although the attribute name could be `foo-bar`, `foo-Bar` or `FOO-BAR`.

**Comment by davidmaxwaterman** [comment]
Hrm, I get what you're saying. The case mapping is done between the attributes on the instance of the element to what is listed in the `attributes` attribute on the `<polymer-element>` tag. I think I misunderstood it completely...I'm not sure how best to make it clearer. Perhaps nothing is required; up to you.
