### ISSUE TITLE
Boolean attributes don't behave as described

### ISSUE THREAD

**Issue by apowers313** [Polymer/docs#1328]
If a Boolean attribute is defined as:
``` javascript
properties: {
    active: Boolean
}
```
And a tag is implemented as:
``` html
<example-tag></example-tag>
```
The result is that `active` is `undefined`, not `false` as [described in the documentation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-serialization).
<hr>
Likewise, if a Boolean value is defined as:
``` javascript
properties: {
    active: {
        type: Boolean,
        value: true
    }
}
```
And used in a tag as:
``` html
<example-tag></example-tag>
```
The value is `true` (not `false` because the attribute isn't assigned), which would run contrary to the same documentation.

It's not clear to me if this is a bug or misleading documentation.

**Comment by arthurevans** [comment]
I think this is  a matter of misleading docs as much as anything. I'm going to Cc: @sorvell @sjmiles for correction, but here's what I think is the case:

Polymer will set a Boolean property from an attribute value, but only in the following circumstances:

- If the attribute is _set_ in the markup, or
- If the attribute changes at runtime (e.g., `setAttribute`).

Since you can't _unset_ them from markup, Boolean properties work best if you use them the way native HTML elements use them: they should always be default false. If you need the opposite behavior, you can either invert the sense of the attribute (i.e., `inactive`), or use a different type (such as the ARIA attributes, which use string values like "true," "false," and "mixed").

**Comment by sjmiles** [comment]
Arthur has got the right information. Here is some background.

For performances reasons, a principle of Polymer is: whenever possible, do no work. 

If a property has no `value` and is not set via bindings or attribute, Polymer will not touch it, and it will remain `undefined`. The absence of an attribute at initialization time therefore triggers no work. Polymer will only react to attribute _changes_.

Since `undefined` is falsey, as a practical matter this generally works out for properties of type Boolean. If you want to avoid undefined you can set the property's default value to `false`.

**Comment by arthurevans** [comment]
Thanks @sjmiles. Will update the docs.
