### ISSUE TITLE
A kitchen sink and screenshots please

### ISSUE THREAD

**Issue by raulgd** [Polymer/docs#1353]
Hi all,

It's weird that I go into the Polymer website, a UI library BTW, and there's absolutely no screenshots, live demo applications or anything at all.
How am I supposed to get at least an idea of how a UI library result looks like with absolutely no UI samples.
I know this is a library which means it's code oriented, but to demo a UI library by just showing code is ridiculous.

**Comment by ebidel** [comment]
Polymer is not a UI library :) Some of Polymer's elements *are* UI components.

FTW, we keep the element catalog separate from Polymer core because it's a different offering. However, I tend to agree that it's not easy to see *all* of Polymer's offerings. Making the decision to use a technology is a lot easier if everything is together and you can see/try before you buy.

https://ebidel.github.io/material-playground/ is one example of a kitchen sink. But in general, I think we could do a lot better of showing off these things on pp.org cc @tjsavage @frankiefu

**Comment by arthurevans** [comment]
Yeah, we used to have a Material Design with Polymer guide in 0.5, but it hasn't been ported to 1.0 yet.

**Comment by arlair** [comment]
Yes, I remembered the old version and was looking for the equivalent for 1.0+. It makes it easier to determine elements I need by scrolling through one page instead of clicking on individual demos. Cheers.

**Comment by arthurevans** [comment]
Opened a separate ticket to port the 0.5 guide to 1.0 guide: #1407.

Inclined to close this ticket if that would meet the request.

**Comment by arthurevans** [comment]
Closing in favor of #1407.
