### ISSUE TITLE
CSS mixins should link to spec

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1409]
https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins should link to http://tabatkins.github.io/specs/css-apply-rule/. Users may not think this is coming, natively!

**Comment by kaycebasques** [comment]
@ebidel how about if I add the sentence in bold below?

...

For this reason, the custom properties shim included in Polymer includes an experimental extension allowing a bag of CSS properties to be defined as a custom property and allowing all properties in the bag to be applied to a specific CSS rule in an element’s local DOM. For this, we introduce a mixin capability that is analogous to var, but allows an entire bag of properties to be mixed in. The extension adheres to the [CSS @apply rule](http://tabatkins.github.io/specs/css-apply-rule/) specification. 

...

**Comment by arthurevans** [comment]
Because it's very new, I'd just say, "proposal" rather than spec (unless @ebidel feels differently). Also, feel free to cut this paragraph down. Remove the "experimental", and replace "bag" with "set"...

 ... custom properties shim also includes support for defining a custom property set, as defined in the <foo bar spec/proposal>. This provides a mixin capability ...

In general, free to debloat any text in the custom properties section :D

**Comment by ebidel** [comment]
Yea. Propsal is good.
