### ISSUE TITLE
The carousel example to explain effective children in local-dom.html is confusing

### ISSUE THREAD

**Issue by mercmobily** [Polymer/docs#1435]
I think there is some room for improvement in the section "Effective children":

1) Why talking about an element without local DOM?

It says "Consider a simple image carousel element with no local DOM". A carousel however is the typical element that would actually have a local DOM, in my opinion. Also, it's not clear at this point in the guide how you can create elements without a local DOM. I ASSUME the writer meant:

```
<script>
  Polymer({
    is: 'simple-carousel',
    attached: function(){
      var l = Polymer.dom( this ).children.length;
      console.log("Length: ", l );
    }
  });
</script>
```

I have never created elements without local DOM, and I assume the styling would do all of the magic. But then again, the CSS would need to live somewhere in the global space, since there is no `<dom-module>`  and no `<template>`.

2) Are we missing out on providing the main message?
# My solution

I (VERY humbly) think the main message here is this:

"There are cases where the _light DOM_ of a widget (and not its template) has a `<content>` tag. This happens for example when a Polymer element is used inside another element's template (as it might well happen in composition)."

An example should follow, but I think it should be a complete example, where you provide the implementation of a super-simple polymer widget (replacing `simple-carousel`) and then encapsulating that super-simple element into another, showing how the super-simple element's _local DOM_ might end up having a `<content>` tag.

This is the code I would use in the example:

```
<dom-module id="element-counter">
  <template>
    <p>This is the element counter!</p>
    <content></content>
  </template>
  <script>
    Polymer({
      is: 'element-counter',
      attached: function(){
        console.log("Children:", Polymer.dom( this ).children );
        console.log("Effective children:", this.getEffectiveChildren() );
        console.log("That's it!");
      }
    })
  </script>
</dom-template>



<dom-module id="complex-widget">
  <template>
    <p>This is a complex widget that includes the element-counter</p>

    <element-counter>
      <content></content>
    </element-counter>

  </template>
  <script>
    Polymer({
      is: 'complex-widget',
    })
  </script>
</dom-template>
```

This way, it's totally clear that if a developer wants his or her widgets to work while used in composition, getEffectiveChildren() is _imperative_. Once again, I think the most important message here is "The light DOM might include `<content>` tags too!".

**Comment by arthurevans** [comment]
Thanks for the feedback. Good suggestions and I agree with several of the points.

It is a confusing API, and the difference between `getEffectiveChildren` and `getDistributedNodes` is subtle. In your example, either one will work. You only see a difference between the two in one of the following circumstances:

-   the element has no local DOM.
-   the element uses no `<content>` tag.
-   the element has one or more `<content>` tags with `select=` attributes.

For a simple element with one `<content>` tag with no select, `content.getDistributedNodes() == element.getEffectiveChildren()`.

Your main takeaway is spot-on: "the light DOM might include `<content>` tags too".

In _most cases_, `getDistributedNodes` gives you what you want—the child nodes that have *actually* been distributed to a particular `<content>` tag. 

In some weird cases, you might want all effective children regardless of whether they've been distributed into your local DOM. That's where you need `getEffectiveChildren`. 

(For example, if your `element-counter` _didn't_ include a `<content>` tag, but did something with its light DOM children programmatically.)

I agree on the more complete examples, too.

**Comment by MeTaNoV** [comment]
+1, I had a hard time getting all of this correctly at the first read! :)

**Comment by mercmobily** [comment]
@arthurevans I would be more than happy to send a PR against the doc, if you agree in principle with what I wrote. I will expand on what I wrote above, and will make sure that the API is explained as clearly as possible.

If you give me the go-ahead, I will get started on this ASAP.

(I am mainly asking in case you were already working on it...)

**Comment by arthurevans** [comment]
A PR would be welcome. I'm not likely to get to this in the near future.

Agree in principle, with the caveats expressed above--the standard getDistributedNodes is probably what you want 90% of the time.

**Comment by mercmobily** [comment]
Hi,

It will be an honour for me to get this done.

Merc.

**Comment by mercmobily** [comment]
Before I commit the change onto my tree, I was wondering if you could please give me some early feedback.

---------------
At this point, it's obvious that an element's local DOM can contain one or several `<content>` nodes, which will be replaced by the element's light DOM in order to create the element's composite DOM, which is what is actually rendered by the browser.

What is less obvious, is that the `<content>` can also be placed in an element's _light DOM_.

For example, take a simple widget:

    <dom-module id="element-counter">
      <template>
        <p>This is the element counter!</p>
        <content></content>
      </template>
      <script>
        Polymer({
          is: 'element-counter',
          attached: function(){
            this.childCount = Polymer.dom(this).children.length;
            console.log( "COUNTER:", this.childCount )
          }
        })
      </script>
    </dom-template>

Using this element is as simple as:

    <element-counter>
      <p>one</p>
      <p>two</p>
      <p>three</p>
    </element-counter>

The three `<p>` elements are the element's light DOM. The element's local DOM places them in the composite DOM thanks to the `<content>` tags.

Now, imagine a case where you have a complex widget that uses our element counter:

    <dom-module id="complex-widget">
      <template>
        <p>This is a complex widget that includes the element-counter</p>

        <element-counter>
          <content></content>
        </element-counter>

      </template>
      <script>
        Polymer({
          is: 'complex-widget',
        })
      </script>
    </dom-template>

The use is the same:

    <complex-widget>
      <p>four</p>
      <p>five</p>
    </complex-widget>

As you can see, in this case the element counter's _light DOM_ doesn't contain actual nodes: instead, it has the `<content>` element. Keep in mind that `<content>` will be replaced by the complex widget's light DOM: in this case, `<p>four</p>\n<p>five</p>`.

As a result, the element counter's function `this.childCount = Polymer.dom(this).children.length;` returns `1` (the element's `<content>` node) rather than `2` (the element's _effective_ children once any `<content>` elements are placed).

So, **even an element's light DOM may contain `<content>` tags if the element is placed into another element's local DOM**.

To get the list of effective child nodes, you can use `getEffectiveChildNodes()`:

    var effectiveChildNodes = Polymer.dom(element).getEffectiveChildNodes();

For convenience, several utility methods are available on the Polymer element prototype:

* `getEffeciveChildNodes()`. Returns a list of effective child nodes for this element.
* `getEffectiveChildren()`. Returns a list of effective child elements for this element.
* `queryEffectiveChildren(selector)`. Returns the first effective child that matches selector.
* `queryAllEffectiveChildren(selector)`. Returns a list of effective children that match selector.

Replacing `children` with the `getEffectiveChildren` method gives you the result you want:

    // ...childCount
    attached: function(){
      this.childCount = this.getEffectiveChildren().length;
    }
---------------

Now, as per your comments... I must be missing something.
you wrote:


> It is a confusing API, and the difference between getEffectiveChildren and getDistributedNodes is 
> subtle.

I think its more than subtle. In fact, they are totally different things, are they not? getEffectiveChildren() will get _all_ children, even in cases where the light DOM has `<content>` .  getDistributedNodes() on the other hand _needs a contentNode to work_. So, while getEffectiveChildren() is used in order to make the element agnostic in terms of what might be in its light DOM, getDistributedNodes() will only tell you what nodes are contained in a specific contentNode.

Unless I got something very wrong, which is VERY possible!

> In your example, either one will work.

Again I am lost here. Really? Because I didn't manage to. They are totally different calls..

>  You only see a difference between the two in one of the 
> following circumstances:

> * the element has no local DOM.
> * the element uses no <content> tag.
> * the element has one or more <content> tags with select= attributes.

And here is where I _really_ lost you. You are comparing two functions that, to my eyes, have very little in common -- ESPECIALLY in terms of what they do in the big picture. To me, `getEffectiveChildren()` is essential to make sure that a Polymer element will access all of its children -- even in cases where the element is placed within another element's local DOM and therefore might well contain `<content>`. On the other hand, `getDistributedNodes()` to me has totally different use cases (for example, you design an element with multiple `<content>` element with `select=`, and want to see what's been placed there).

So, to me *any* comparison will bring confusion... But again, I am likely to be missing something here!
(In which case I apologise!)

Merc.

**Comment by arthurevans** [comment]
No apologies necessary! First off, thank you for your efforts to make this whole section clearer. 

I think the missing piece of information here is the notion that distributed nodes are _fully_ distributed.  Suppose I call `getDistributedNodes` on `element-counter`'s `<content>` tag. If `element-counter`'s light children include a `<content>` tag, that `<content>` tag is replaced by _its_ distributed nodes, and so on, recursively, all the way up the tree. So in your use case, `element-counter.$.content.getDistributedNodes()` is by definition identical to `element-counter.getEffectiveChildNodes()`. 

So hopefully that covers the first point.  If you have a single content tag with no select, calling `getDistributedNodes` _on that content tag_ returns the same results as calling `getEffectiveChildNodes` _on the element_. The semantics are different, but the results are the same.

You're right that the difference in semantics between the two methods isn't that subtle. But I think the differences between the use cases is.

In your first example, I would be inclined to use `getDistributedNodes` on the element-counter's `content` tag. I lean that way because `getDistributedNodes` is the native API. And what I really _want_ is the list of nodes _that are distributed in to this point in my local DOM_. That list may be identical to the node's effective children, but that's not the way I think about it. I think about it as distributed content—that's the way I access it, that's the way I style it. 

Let me try to lay out an example to explain what I mean. Let's go back to that carousel example, but give this one local DOM:

    <template>
      <div id="images">
        <content id="images"></content>
      </div>
    </template>

Like I said, here, both methods can give you the same information. But I would argue that _conceptually_, my component is interested in _the number of elements distributed into the insertion point_.

Now, imagine in the next version of my element, I decide to add a title. Now my local DOM is going to look like this:

    <template> 
      <div id="lightbox">
        <h2 id="title"><content select=".title"></content></h2>
        <div id="images">
          <content id="images"></content>
        </div>
      </div>
    </template>
        
Now all of the sudden `getEffectiveChildNodes` isn't giving me the right thing. But if I'm using `this.$.images.getDistributedNodes()`, the semantics remain the same, and I'm still getting the results I want.

So that's why it seems to me if you're using one or more `<content>` tags, you probably want the semantics of `getDistributedNodes`. I've been working with Polymer for a while now, and I don't really remember any instances where I wanted the particular semantics of `getEffectiveNodes`, where `getDistributedNodes` wouldn't work just as well. But there are plenty of instances of the opposite case, where `getEffectiveChildNodes` isn't useful.

That's why I've tried to outline some (slightly rare) use cases where `getEffectiveChildNodes` gives you something that `getDistributedNodes` can't. **If you can think of a better real-world example for this than the carousel-with-no-local-DOM, that would be awesome.** Because I'm having trouble coming up with non-contrived examples.

Incidentally, under the covers what `getEffectiveChildNodes` does is iterate through `.childNodes`, and replaces each `<content>` element with its distributed nodes. `getDistributedNodes` does the heavy lifting:

https://github.com/Polymer/polymer/blob/cb68ce54ebdcfb2d6f7342e801574881fb158076/src/lib/dom-api.html#L487

**Comment by arthurevans** [comment]
Whew! Hope that helps :smile:

**Comment by mercmobily** [comment]
Hi,

First of all, please accept my apologies for harassing you for something that is likely minor.

> I think the missing piece of information here is the notion that distributed nodes are fully distributed. Suppose I call getDistributedNodes on element-counter's <content> tag. If element-counter's light children include a <content> tag, that <content> tag is replaced by its distributed nodes, and so on, recursively, all the way up the tree. So in your use case, element-counter.$.content.getDistributedNodes() is by definition identical to element-counter.getEffectiveChildNodes().

> So hopefully that covers the first point. If you have a single content tag with no select, calling getDistributedNodes on that content tag returns the same results as calling getEffectiveChildNodes on the element. The semantics are different, but the results are the same.

My big issue here is the sentence: _Suppose I call getDistributedNodes on element-counter's <content> tag_. 
What I don't quite get is this: I really, really want element-counter to work when used like this:

**Comment by mercmobily** [comment]
Hi,

First of all, please accept my apologies for harassing you for something that is likely minor.

I will only address the first point you made, to keep this discussion tight. Also, I suspect I might be missing something... my questions below will clarify my doubts.

> I think the missing piece of information here is the notion that distributed nodes are fully distributed. Suppose I call getDistributedNodes on element-counter's <content> tag. If element-counter's light children include a <content> tag, that <content> tag is replaced by its distributed nodes, and so on, recursively, all the way up the tree. So in your use case, element-counter.$.content.getDistributedNodes() is by definition identical to element-counter.getEffectiveChildNodes().

> So hopefully that covers the first point. If you have a single content tag with no select, calling getDistributedNodes on that content tag returns the same results as calling getEffectiveChildNodes on the element. The semantics are different, but the results are the same.

My big issue here is the sentence: _Suppose I call `getDistributedNodes` on element-counter's <content> tag_. 
What I don't quite get is this: I really think element-counter should work when used like this:

    
    <element-counter>
      <p>one</p>
      <p>two</p>
      <p>three</p>
    </element-counter>

Or like this:

    
    <dom-module id="complex-widget">
      <template>
        <p>This is a complex widget that includes the element-counter</p>

        <element-counter>
          <content></content>
        </element-counter>

      </template>
      ....

To me, the point of `getEffectiveChildNodes()` is that it will work regardless of how children are added. Using `element-counter.$.content.getDistributedNodes()` will not work in "USE 1" because there is no `<content>` there to speak of -- the light DOM has elements directly placed.

Isn't it important to make elements agnostic in terms of what their light DOM contains? ('real' elements or '<content>' elements that will be expanded). And isn't that the point of `getEffectiveChildren()`?

Merc.

**Comment by arthurevans** [comment]
It will work fine in USE 1. A couple of points on which I may have introduced confusion, however:

- Note that that should be something like `Polymer.dom(this.$.content).getDistributedNodes()`.
- Also, that `this.$.content` assumes that your content tag has an ID of `content`, which your original element didn't.

Anyway, here's my version of `element-counter`:

    <dom-module id="element-counter">
      <template>
        <p>This is the element counter! It has {{childCount}} distributed nodes.</p>
        <content></content>
      </template>
      <script>
        Polymer({
          is: 'element-counter',
          attached: function(){
            this.childCount = Polymer.dom(this.$.content).getDistributedNodes().length;
            console.log( "COUNTER:", this.childCount )
          }
        })
      </script>
    </dom-template>

So, the `element-counter` has a `<content>` tag in its local DOM. That's the one we're calling `getDistributedNodes` on. (In previous replies, I forgot to include the `Polymer.dom` calls, which may add confusion. Actually, there are shortcuts for this that I'd forgotten, `getContentChildren` and `getContentChildNodes`, which you can find in the API ref.)

Anyway. In this instance, it doesn't matter whether the light DOM contains normal children, `<content>` tags, or both--content tags are replaced by their distributed nodes during the distribution process. 

Here's a jsbin of this in action. The numbers may be a little confusing--that's because the count includes all nodes, and it's counting the extra text nodes added by the whitespace in `complex-widget`'s template.

http://jsbin.com/dabuqor/2/edit?html,console,output

If we add `strip-whitespace` to the `complex-widget`, you'll see the node counts now match, because `complex-widget`'s template isn't adding any extra text nodes:

http://jsbin.com/dabuqor/3/edit?html,console,output

Finally, for ease of use, let's shorten that big call to `getContentChildren`--which only returns elements, so we'll get a result maybe more like we expected:

http://jsbin.com/dabuqor/5/edit?html,console,output

If your element counter _doesn't_ want to display its children, then you have `getEffectiveChildren` to fall back on:

http://jsbin.com/dabuqor/6/edit?html,console,output

BTW, if you were calling `getDistributedNodes` without using `Polymer.dom`, I apologize for the confusion. That's going to give you bogus results on Chrome if you're running in the (default) shady DOM mode (and crash on other platforms).

**Comment by mercmobily** [comment]
Thank you for spending this time clarifying things. Working on a new text so that all this is clear. Sorry for not "getting it" straight away!

**Comment by mercmobily** [comment]
OK, now I get it (I hope) 100% especially thanks to Arthur's help. Arthur, can you please:

* Check that I didn't write any BS
* Complete the one sentence I am having a problem with (see CAPS at the end of the file)
* Check that I am not using Australian spellings anywhere (that's where I live, sorry!)
* The code follows your standards etc. (I think it does...)

...and I think it's a rewrite!


At this point, it's obvious that an element's local DOM can contain one or several `<content>` nodes, which will be replaced by the element's light DOM in order to create the element's composite DOM, which is what is actually rendered by the browser.

What is less obvious, is that the `<content>` can also be placed in an element's _light DOM_. This has some interesting implications.

For example, take a simple widget:

    <dom-module id="element-counter">
      <template>
        <p>This is the element counter! The count is: {{childCount}}</p>
        <content id="c"></content>
      </template>
      <script>
        Polymer({
          is: 'element-counter',
          attached: function(){
            this.childCount = Polymer.dom(this).children.length;
            console.log("COUNTER:", this.childCount);
          }
        })
      </script>
    </dom-template>

Using this element is as simple as:

    <element-counter>
      <p>one</p>
      <p>two</p>
      <p>three</p>
    </element-counter>

The three `<p>` elements are the element's light DOM. The element's local DOM places them in the composite DOM thanks to the `<content>` tags.

Now, imagine a case where you have a complex widget that uses our element counter placing it in its local DOM:

    <dom-module id="complex-widget">
      <template>
        <p>This is a complex widget that includes the element-counter</p>

        <element-counter>
          <content></content>
        </element-counter>

      </template>
      <script>
        Polymer({
          is: 'complex-widget',
        })
      </script>
    </dom-template>

The complex widget is used in the exact same way:

    <complex-widget>
      <p>four</p>
      <p>five</p>
    </complex-widget>

As you can see, in this case the element counter's _light DOM_ doesn't contain actual nodes: instead, it has the `<content>` element. Keep in mind that `<content>` will be replaced by the complex widget's light DOM: in this case, `<p>four</p>\n<p>five</p>`.

As a result, the element counter's function `this.childCount = Polymer.dom(this).children.length;` returns `1` (the element's `<content>` node) rather than `2` (the element's _effective_ children once any `<content>` elements are placed).

So, **even an element's light DOM may contain `<content>` tags if the element is placed into another element's local DOM. Therefore, you should never trust `element.children`**

To get the list of effective child nodes, you can use `getEffectiveChildNodes()`:

    var effectiveChildNodes = Polymer.dom(element).getEffectiveChildNodes();

For convenience, several utility methods are available on the Polymer element prototype:

* `getEffeciveChildNodes()`. Returns a list of effective child nodes for this element.
* `getEffectiveChildren()`. Returns a list of effective child elements for this element.
* `queryAllEffectiveChildren(selector)`. Returns a list of effective children that match selector.
* `queryEffectiveChildren(selector)`. Returns the first effective child that matches selector.

Replacing `children` with the `getEffectiveChildren` method gives you the result you want:

    // ...childCount
    attached: function(){
      this.childCount = this.getEffectiveChildren().length;
    }

So, `element.getEffectiveChildren()` will return the element's children after resolving any `<content>` tag in the element's light DOM.

Note that using `getContentChildren()` would have achieved the same result:

    // ...childCount
    attached: function(){
      this.childCount = this.getContentChildren('#c').length;
    }

Since it will return all of the nodes in the `<content>` tags with id `c`.

There are some cases where they are not equivalent and you cannot use `getContentChildren()`:

* the element has no local DOM. [HELP! WHAT WOULD AN EXAMPLE BE HERE? I HAVE NEVER MADE AN ELEMENT WITHOUT LOCAL DOM AND CANNOT REALLY THINK OF A PRACTICAL USE]
* the element uses no `<content>` tag. For example, the element might not include its light DOM children using a `<content>` tag, and do something programmatic with them instead. In this case, you cannot use `getContentChildren()` since you don't have a `<content>` tag
* the element has one or more `<content>` tags with `select=` attributes. In this case, `getContentChildren()` will need to be used on each `content` tag and won't return the full list of children (which `getEffectiveChildren()`, on the countrary, will return).

As you can see, they are less frequent (although possible) cases where you actually _need_ `getEffectiveChildren()`. Note that in most cases `getDistributedNodes()` gives you what you want -- the child nodes that have _actually_ been distributed to a particular `<content>` tag.

**Comment by mercmobily** [comment]
BTW, if you don't feel that my writeup is OK for you, feel free to scrap it and close the issue. No had feelings, HONESTLY!

**Comment by arthurevans** [comment]
Sorry @mercmobily I had a killer cold for a couple of weeks and got way behind on reviewing stuff. Will try to catch back up this week.

**Comment by mercmobily** [comment]
Oh no worries at all, get better! I was just making sure that there was absolutely no stress in case you wanted to scrap what I wrote :dancer:

**Comment by mercmobily** [comment]
Is this going to be used...? Just checking!

**Comment by arthurevans** [comment]
We have a new shadow DOM concepts chapter in 2.x, and the new shadow DOM v1 standards are different than the v0 standards we were talking about here. So I'm going to go ahead and close this.

Hopefully the new docs are clearer than the old ones. Thanks for keeping us honest, @mercmobily!
