### ISSUE TITLE
Properties: make it clear observers should be used for multiple properties

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1492]
From http://rvcode.com/javascript/2016/01/09/polymer-mind-the-properties-init-order.html.

The misconception is that there's an ordering to how property changed handlers are called. If you move properties around in `properties`, the order of callbacks can change. For observers that also need other properties, `observers` with those dependencies are the way to go. 

Not sure how, but maybe this needs to be called out better in the docs if people are running into the same issues early on.

**Comment by kaycebasques** [comment]
@arthurevans @ebidel what's a good title to sum up this info? I'm thinking "Always include all property dependencies in observer arguments" or something like that...

**Comment by arthurevans** [comment]
Yes. Although I'd say "dependencies," since they can be properties or paths... 

For simple property observers, there should be a note that says, "A property observer shouldn't rely on any other properties (that is, an observer for `foo` shouldn't reference `this.bar`). Polymer doesn't guarantee that properties are initialized in any particular order. If your observer relies on multiple property values, use a multi-property observer(link)."

Or words to that effect.

For multi-property observers, something like you said. 

There's probably one exception, which is that if the observer relies on a property, but doesn't require it to be initialized, you can access those values in the observer function. However, the observer is only called when its identified dependencies change.

Does that make any sense to you, Eric? Or should they just bite the bullet and add non-undefined defaults for everything?

i.e.:

```
myObserver: function(oneValue, twoValue) {
  if (this.sideEffect) {
    ... do something with oneValue and twoValue
  } else {
    ... do something else
 } 
```

This runs when oneValue or twoValue changes, regardless of whether sideEffect is set or not, but sideEffect changes the outcome.
