### ISSUE TITLE
Add documentation for mixin contents

### ISSUE THREAD

**Issue by Sese-Schneider** [Polymer/docs#1531]
Example: https://elements.polymer-project.org/elements/paper-tabs?active=paper-tab

![chrome_2016-02-10_00-50-51](https://cloud.githubusercontent.com/assets/14337484/12934645/658d8e3c-cf90-11e5-9b6d-3b902888b453.png)

It took me around 30min to find out that you have to apply `background-color` to the mixing to change the color.  Please document the mixins!

Althought there is no doc for the var `--paper-tabs-selection-bar-color`

**Comment by mercmobily** [comment]
@Xeselaro Just to check, is this issue about the lack of documentation of `--paper-tabs-selection-bar-color`?

If you read the file `paper-tabs/paper-tabs.html`, you will see that it _is_ documented. However, for some reason, it doesn't seem to make it to the generated documentation (!) which stops at:

    <style is="custom-style">
     .link {   

But the docs actually continue!

@arthurevans Is this something you could look at? Could the `@apply` statement confuse the doc generator? The documentation is effectively truncated right now...

**Comment by Xeselaro** [comment]
@mercmobily My real issue is about that the "normal" user, who don't want to read the exact documents for each element and want to lockup things at [elements.polymer-project.org](elements.polymer-project.org) has **no** idea what the mixin contents are and how to apply custom variables.

I didn't see the doc fpr `--paper.-tabs-selection-bar` sorry, this was my fault.

**Comment by arthurevans** [comment]
@mercmobily Yes, that's a bug/limitation in the doc generator: https://github.com/Polymer/hydrolysis/issues/139

Currently, all we can do is work around this issue on a case-by-case basis. I've opened a bug to do that for paper-tabs: https://github.com/PolymerElements/paper-tabs/issues/132

@Xeselaro A mixin can hold any set of CSS properties, and there are [quite a few available](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference), so I'm not sure what kind of guidance we could put here. Maybe there's some missing conceptual information on mixins?

**Comment by Xeselaro** [comment]
@arthurevans Yeah, general information what to do with mixins were great. I'm not a studied developer and sometimes i don't know some technical therms... Thanks for your help!

**Comment by mercmobily** [comment]
@Xeselaro If you have a look at the docs, each element gives you a pretty good idea of what to do in terms of styling. With polymer, the way things are styled are via [custom CSS properties and custom CSS mixins](https://www.polymer-project.org/1.0/docs/devguide/styling.html#xscope-styling). Then, each element has a "Styling" section that tells you how to style it. For example, see [paper-button](https://elements.polymer-project.org/elements/paper-button) and [paper-checkbox](https://elements.polymer-project.org/elements/paper-checkbox).

Polymer does a pretty good job at covering, in the "Styling" section of an element, all the custom CSS properties. I haven't yet seen an element that mixes in a CSS mixin or uses a properties without a reference in the "Styling" section of its documentation. However, you do need to know how to use custom properties and Polymer -- which you can by reading the section I linked above in the documentation.

OK, you can say "What about tabs" :D And you'd be right! But in that case, that's because of a bug in the documentation generator -- sorry about that! Work is being done to get that fixed.

:D

**Comment by TheBolmanator** [comment]
I would like to echo every observation made by Xes'.  Imagine a world where people want to _still_ have labels to the left of their input fields.  

I would like to ask for one example (complete and working in a demo) that shows some of these mixins actually working. My specific request would be for the --paper-input-prefix to be styled (setting the "width='2in'".  Or even better still would be to have a paper-input with a label located to the left (old school) that can have the font-family set different from the input field.  Basically I want what used to be trivial.  

https://elements.polymer-project.org/elements/paper-input?active=paper-input-container

If Polymer mixins aren't better documented (and I don't consider the above discussed notes to be documentation) with fully demonstrated examples covering a number of polymer elements, I fear we are doomed to an universe of apps built using these "custom-elements" that are homogeneous and what we found so engaging last year will be an annoyance next.

Another for instance, how does one set the on focus line to match the width of the input field, or set the on-focus-line-transition from center outward to a left to right.

As I see it, unless the Polymer team gets serious about providing some response to this need for documentation and examples of what can and cannot be performed using mixins, will be inclined to return to "custom-elements", as much as I would like to join the Roboto crew.

**Comment by Xeselaro** [comment]
@TheBolmanator this is a great idea! The polymer team should improve the documentation in this way!

**Comment by katejeffreys** [comment]
To help with prioritization, I will close this issue in 7 days with no docs changes unless requested otherwise. Thanks!
