### ISSUE TITLE
editable-name-tag.html in "quick tour" has incorrect imports (they are correct in the plunker linked code)

### ISSUE THREAD

**Issue by azakus** [Polymer/docs#1536]
_From @robokyle on February 1, 2016 16:20_

I've been following the polymer quick tour from scratch in plunker, following the code in the tutorial, not from the plunker links. Couldn't get iron-input to load:
GET http://run.plnkr.co/EkeSvJ2gUlBk4kt9/bower_components/iron-input/iron-input.html 404 (Not Found)
run.plnkr.co/:1 GET http://run.plnkr.co/EkeSvJ2gUlBk4kt9/bower_components/polymer/polymer.html 404 (Not Found)

But discovered that the plunker link from the tutorial contains the correct code.

So this is what should be at the top of the page to make the code work in plunker - 

<link rel="import"
      href="http://www.polymer-project.org/1.0/components/polymer/polymer.html">

<link rel="import"
      href="http://www.polymer-project.org/1.0/components/iron-input/iron-input.html">

Very nice tutorial/intro to the concepts, by the way!

_Copied from original issue: Polymer/polymer#3356_

**Comment by arthurevans** [comment]
Thank you! Glad you liked it and sorry for the confusion.

Our expectation with the quick tour was that people would either just look at the code, or would click through to the plunker links and work with the individual examples... We never considered that someone might go through it copy-and-paste style.

So the URLs that we show are the "correct" ones in the sense that they'd be the ones you use if you installed the packages locally using Bower. 

Note to self: when polygit stabilizes, we should replace all of these URLs with polygit URLs instead of linking back to the site.

**Comment by robokyle** [comment]
Sure thing, I've definitely found the code examples and the plunker
environment are great for interactive learning! And good to know that this
is how it would be used through Bower.
