### ISSUE TITLE
Add documentation on how to listen for events in distributed children

### ISSUE THREAD

**Issue by mercmobily** [Polymer/docs#1543]
The Events section of the documentation doesn't mention at all how to listen to events in distributed children.
I came up with:

````
   <x-el>
     <p id="main">I am the main paragraph</p>
     <p id="secondary">I am the secondary paragraph</p>
   </x-el>
  
  <x-el>
     <p id="main">AGAIN I am the main paragraph</p>
     <p id="secondary">AGAIN I am the secondary paragraph</p>
   </x-el>
  
  <dom-module id="x-el">
    <template>
      <content id="test"></content>
      <p>{{message}}</p>
    </template>
    <script>
      Polymer({
        is: 'x-el',
        properties: {
          message: {
            type: String,
            value: 'hi'
          },
        },
        attached: function(){
          this.message = "Attached!";
          var lightPrimary = this.getContentChildren('content')[0];
          this.listen( lightPrimary, 'tap', 'onTap');
        },
        onTap: function(e){
          this.message="Primary tapped!";
        }
        
      });
    </script>
  </dom-module>
````

[Here as a JSBIN](http://jsbin.com/lajunu/edit?html,output)

(I know, I don't stop listening on `detach`...)
So, questions:

1) Is this the way to go? Is there no way to listen to distributed children automatically?
2) Shall I make a PR and document this? (with better code)

Bye

**Comment by arthurevans** [comment]
In general, elements that want to listen for events from their distributed children (for example, an `iron-selector` or its relatives) simply use a listener at the host element level (using `this.listen` or the `listeners` object). You get the events as they bubble up, so you only need to add one listener. I think this is the simplest case, and also by far the most common.

If you want to _only_ listen for events from the distributed children, the easiest thing would be to wrap the `content` element in a div and add a declarative event listener to the wrapper, like this: 

http://jsbin.com/rixujet/1/edit?html,output

There's not really anything Polymer (or shadow DOM) specific in this; it's just working with the DOM.

To my mind, the sample you wrote up would be an anti-pattern for two reasons:

1) You're listening on a single content child based on its position, so the element is assuming a certain structure for its light DOM children. If you want to give a child special treatment, you're better off using `<content select=`.

2) Consider what happens when the user mutates the light DOM, like this:

    var child1 = Polymer.dom(xEl).children[0];
    var child2 = Polymer.dom(xEl).children[1];
    Polymer.dom(xEl).removeChild(child1);
    Polymer.dom(xEl).insertBefore(someNewChild, child2);

In this case, you have a memory leak (child1 can't be garbage collected, because you have a listener attached to it), and you don't have an event listener attached to the element that replaced it.

**Comment by mercmobily** [comment]
You are absolutely right. Sorry for wasting your time...
