### ISSUE TITLE
TODO in head should be removed

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/docs#1547]
When browsing the HTML code, I came accross [this TODO](https://github.com/Polymer/docs/blob/be6d93c36b87de17d8b91583d522643513850134/_includes/head.html#L46-L47). The [linked issue](https://github.com/polymer/polymer/issues/391) is closed, so I guess the TODO can be removed?

**Comment by arthurevans** [comment]
You're probably right. Although, as it turns out, deleting the following line actually breaks the 0.5 homepage. So... At this point I'm ill-inclined to do the archaeology necessary to remove this (otherwise harmless) link tag. You're welcome to submit a PR removing the TODO note itself, however, as we're definitely not going TO DO that anymore.
