### ISSUE TITLE
Overlapping buttons when the screen size is reduced

### ISSUE THREAD

**Issue by azakus** [Polymer/docs#1549]
_From @srgummad on August 23, 2015 17:19_

The buttons near the footer and above it overlap when the screen size is reduced. The same is observed when the site is opened in a mobile.
![polymer-issue](https://cloud.githubusercontent.com/assets/10765108/9429284/ea0c25c0-4998-11e5-89d4-63f21eb935ed.JPG)

Also for these two buttons....

![polymer-issue2](https://cloud.githubusercontent.com/assets/10765108/9429285/fe82eab6-4998-11e5-9833-2bd49a2b7fd0.JPG)

_Copied from original issue: Polymer/polymer#2351_

**Comment by azakus** [comment]
@arthurevans I know we're going to redo the landing site at some point. Leaving this up to you if we bother fixing this before that.

**Comment by arthurevans** [comment]
Yeah, this is annoying. But I think since we're planning on redoing the site, we're not going to put any more work into fixing non-critical problems on the existing site. We're still doing a lot of work on content, but I don't want to put any more work into the old infrastructure. 

(Would be happy to accept a PR for this kind of issue, but I just don't have any bandwidth to work on them.)
