### ISSUE TITLE
The Polymer site is unaccessible.  I have tested it with keyboard interfaces and screen readers and it is an unaccessible site.

### ISSUE THREAD

**Issue by azakus** [Polymer/docs#1568]
_From @haltersweb on March 1, 2016 22:57_

_Copied from original issue: Polymer/polymer#3487_

**Comment by azakus** [comment]
@haltersweb Which browsers and screenreaders did you use? 
The main site is undergoing a complete rewrite, and we should make a test matrix in the future.
Our current list of screen readers is NVDA and JAWS for windows, VoiceOver for OS X, and ChromeVox for ChromeOS.

**Comment by samccone** [comment]
@haltersweb I am also curious because I just did a quick test and I am able to use the site with the system screenreader on OSX

**Comment by arthurevans** [comment]
I just tried the left navigation with the keyboard. It was always weird and awkward, but now I can't get it to work at all. @azakus @samccone is the left nav working for you?

**Comment by haltersweb** [comment]
Hi Sam,

Thanks for your reply.  The main issues were:

1. not being able to use the left nav elements with only a keyboard, and
2. Color contrast

I tried a few things:

1) VoiceOver on Chrome for Macbook
2) VoiceOver on Safari for Macbook
3) VoiceOver on iPad and iPhone 6 (couldn't test because every time I navigated to a new page it would redirect me back to the polymer homepage)
4) NVDA on Firefox
5) tested color contrast which it didn't pass

Are you at the CSUN conference?  I would be interested in speaking with you'all further about Polymer accessibility.

Adina Halter
Sr. Product Manager and Chief Technologist, Accessibility
Comcast
Adina_Halter@cable.comcast.com

**Comment by samccone** [comment]
@robdodson is!

**Comment by robdodson** [comment]
Yep I'm at CSUN if you want to try to meetup.

The current Polymer site is extremely old and built with pre Polymer 0.5 elements. We're in the process of throwing the whole thing away and starting over with the latest and greatest stuff. When that site was originally written our team was pretty weak in accessibility knowledge. Since then we've growing a ton in this area. The Polymer 1.0+ elements have all been reviewed by Google's accessibility team and work MUCH better. Similarly, I've done my best to skill up in accessibility and am currently producing a course on teaching developers the fundamentals of a11y. I can assure you that our team will produce a solid, accessible experience with the new site that's rolling out next quarter.

**Comment by haltersweb** [comment]
Hi Rob,

So glad to hear about the update!  Can't wait to see it.

I am in charge of evaluating Polymer for use at Comcast NBC U. Would love
to chat Polymer and accessibility with you.

Are you available for lunch today?

Adina

**Comment by haltersweb** [comment]
Actually an early dinner would work better if that works for you. Say, 4:15?

Adina

**Comment by robdodson** [comment]
Yep! Do you want to shoot me an email and we can sync up? I'm
robdodson@google

**Comment by robdodson** [comment]
Ah I'm flying out at 6:30 but maybe we could grab coffee?

**Comment by haltersweb** [comment]
LOL, flying out at 7:30.  Let's do Starbucks at the airport.

What time do you head out for the airport?

My cell is 267-658-0261

--Adina

**Comment by haltersweb** [comment]
haltersweb has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=946634442539-bpj9bmemdvoedu8d3or6c69am3mi71dh.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.pro%2Fg.php&customparam=customparam>
