### ISSUE TITLE
Firebase deployment doc needs significant update

### ISSUE THREAD

**Issue by dandv** [Polymer/docs#1629]
After the release of firebase CLI 3.0, the Firebase deployment instructions at https://www.polymer-project.org/1.0/start/psk/deploy no longer work, and using an old firebase.json triggers errors like

> !  "firebase" key in firebase.json is deprecated. Run firebase use --add instead
> !  Deprecation Warning: Firebase Hosting configuration should be moved under "hosting" key.

Those instructions are linked from https://github.com/PolymerElements/polymer-starter-kit#tutorials

https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-firebase-pretty-urls.md will also need an update.

**Comment by arthurevans** [comment]
@kaycebasques Can you take a look at this? I'm not sure if this was reported against your version of the doc or the one @kevinpschaaf updated for Toolkit.

We should also probably (at least temporarily) remove the links from the PSK README since the tutorial doesn't talk about PSK per se anymore. (At least until we reconcile PSK with the new CLI & templates.)

**Comment by arthurevans** [comment]
Ah, I see what's going on (partially): the /psk/ directory got removed from the leftnav, but not deleted, so direct links to https://www.polymer-project.org/1.0/start/psk/deploy are loading the older doc.
