### ISSUE TITLE
document.createElement() advice is broken

### ISSUE THREAD

**Issue by annevk** [Polymer/docs#1705]
https://www.polymer-project.org/1.0/docs/devguide/registering-elements conflicts with https://dom.spec.whatwg.org/#dom-document-createelement leading to compatibility issues in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1294100.

Please fix this before we have to add overloads to standards...

**Comment by ebidel** [comment]
From reading, it looks like this is a spec change in the last couple of years. Custom elements v0 has [worked](http://www.html5rocks.com/en/tutorials/webcomponents/customelements/#usetypeextension) with a 2nd arg string param for many years, so I'm not sure if we can recommend the new version to users just yet. It simply won't work in Blink.

Is there a chromium issue to update `d.createElement` to the latest spec?

**Comment by annevk** [comment]
The main problem is that 2nd arg being a string will throw in new implementations. Because you used the standard `document.createElement()` API with a non-standard argument, you have effectively broken that method to some extent. That's not very friendly.

I don't know about a Chromium issue.

**Comment by ebidel** [comment]
My point was that this was spec this way at one point and implemented in an engine.

**Comment by slightlyoff** [comment]
I have some dumb questions!:

 - is the only current valid property for options really [`is`](https://dom.spec.whatwg.org/#dictdef-elementcreationoptions)?
 - how bad is an overload here?
 - how quickly can Polymer move to the dict form?
 - what's the global usage of the strong-arm form? Seems that contextualises any call for urgency.

Can we schedule some time on a call for us to explore solutions together?

**Comment by arthurevans** [comment]
Neither Chrome nor the Custom Elements v0 polyfill supports the object argument at present, so we can't just change the recommendation to the new format.

This version of Polymer only works with Custom Elements v0, which I thought was only implemented in Chrome. Does Firefox implement v0, or only the v1 spec? If it only supports v1, Polymer 1.0 would need to use the v0 polyfill on Firefox anyway.

The next major version of Polymer will support the v1 spec and no doubt the now-canonical second argument. So I wonder whether this is actually an issue with any actual code in practice.

**Comment by annevk** [comment]
@arthurevans the fact that Firefox gets bug reports about sites breaking (the moment we started trying to ship v1) means the polyfill isn't working or not consistently deployed.

**Comment by annevk** [comment]
@slightlyoff yes, medium, ?, ?, I rather discuss here and in https://github.com/w3c/webcomponents/issues/544 since the likely outcome is just accepting the overload (or dropping support for custom builtins and align with WebKit).

**Comment by arthurevans** [comment]
@annevk You're right, that seems to me like a polyfill issue. Maybe @azakus or @sorvell would be familiar with it? Since one form doesn't work in Chrome, and the other doesn't work in Firefox, it seems like an overload or a change to the polyfill would be a reasonable approaches to prevent breaking existing code. 

Personally, I can only change the docs here, and I don't think there is (at present) any satisfactory way to solve this with docs alone.

**Comment by robdodson** [comment]
Sorry for the late reply. I've been discussing what we should change to fix
this issue with members of the team. Some combination of a warning in Blink
when folks use the old syntax, updating the v0 polyfill, and updating our
docs. Many folks have been travelling this week but we're meeting this
Friday to come up with the final list of action items which I'll post here
so we can all discuss.

Because type extension are so valuable for accessibility and progressive
enhancement I'd really love for us to come to a consensus that makes
everyone happy so we can keep them in.

I'm also trying to reach out to the folks who filed the original bug to see
what their usage is like. I suspect that imperative usage of the v0
createElement call with two strings may be low but don't have exact data on
that. Not sure if FF has stats on this but I'd be interested to see them if
they exist.

**Comment by annevk** [comment]
We don't have telemetry for `createElement()` as far as I know. @smaug--- do you know better?

**Comment by smaug----** [comment]
I'm not aware us having telemetry on this.

**Comment by ebidel** [comment]
ce v1 polyfill work is done: https://github.com/webcomponents/custom-elements/pull/9

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by annevk** [comment]
As far as I know this problem hasn't gone away.

**Comment by robdodson** [comment]
Small consolation but I reached out to the folks who filed the original issue and if I remember correctly they weren't using web components or looking at our docs. They were just doing something weird if I recall.

**Comment by katejeffreys** [comment]
Is this a documentation issue? If so, please briefly outline how a change to the docs can resolve this, and I will get on it.

**Comment by annevk** [comment]
@katejeffreys I'm not sure it's exclusively a documentation issue. The problem is that https://www.polymer-project.org/1.0/docs/devguide/registering-elements#type-extension conflicts with the standardized signature of `createElement()`, which doesn't accept a string as second argument.

The note present there should maybe be expanded that `createElement()` invoked with the second argument being a string might end up throwing an exception in browsers that implement native custom elements or some such, not sure.

**Comment by arthurevans** [comment]
Since this is only in the 1.x docs, I don't think it's a big deal. The entire 1.x doc set describes the v0 custom elements and shadow DOM specs, and this code should work find as long as you load the custom elements v0 polyfill (and if you don't load it, 1.x won't run anywhere except Chrome and Opera).

I added a note to clarify that the syntax we use here is wrong—but you should use it anyway if you're using 1.x.

**Comment by domenic** [comment]
You should not use it, though, if you're using 1.x. By doing so you are hurting the evolution of the web and preventing browsers from implementing customized built-in elements.

Ideally Polymer would ensure that none of their consumers, no matter their library version, ever use this pattern. Maybe that requires a patch release to 1.x or something, so that the polyfill no longer accepts this? It seems at the very least it requires not producing docs that say "use this anyway".

If that can't be accomplished, I think we may not be able to get customized built-in elements shipped, which from what I understand would be disappointing to at least some Polymer folks. (/cc @notwaldorf)

**Comment by arthurevans** [comment]
@domenic Currently, Chrome accepts the string second argument without issuing a deprecation warning. And the web components v0 polyfills don't accept an object as the second argument. So users don't really have a choice right now.

Polymer 1.x code will only run on browsers that support document.registerElement, or with the v0 polyfills. Using `createElement` with an object for the second argument will cause users' code to break anywhere it's polyfilled.

I think if Chrome wants to deprecate this, it should be deprecated in Chrome, and a bug filed against the web components polyfill.

**Comment by domenic** [comment]
Since the v0 "polyfill" is for a non-standard feature, I think that polyfill should be modified to no longer accept the string argument.
