### ISSUE TITLE
Update Deploy with Firebase with HTTP/2

### ISSUE THREAD

**Issue by abdonrd** [Polymer/docs#1752]
Announce: [HTTP/2 comes to Firebase Hosting](https://firebase.googleblog.com/2016/09/http2-comes-to-firebase-hosting.html)

In the docs: Build an app with App Toolbox > Step 4. Deploy > [Deploy with Firebase](https://www.polymer-project.org/1.0/start/toolbox/deploy#deploy-with-firebase)

Especially mention to Server Push for PRPL pattern.

cc/ @arthurevans @robdodson

**Comment by abdonrd** [comment]
Friendly ping to @arthurevans and @robdodson. 🙂

**Comment by katejeffreys** [comment]
Thanks for raising this, @abdonrd. To help me understand better, is the purpose of this issue to document the availability of HTTP/2 in Firebase in order to tell developers that they can use this to implement the PRPL pattern?

Would it be better to update this page instead, or as well? https://www.polymer-project.org/1.0/toolbox/server#background-http2-and-http2-server-push

**Comment by abdonrd** [comment]
@katejeffreys exactly! How to setup a Polymer project with the PRPL pattern in Firebase using HTTP/2 and Server Push.

Maybe "Deploy with Firebase" is a better place (with any reference to "Background: HTTP/2 and HTTP/2 server push"). I say this to keep this page free of services.

**Comment by johnlim** [comment]
Hi,
The latest docs seem to steer away from mentioning how to deploy to firebase using `unbundled` builds, using HTTP2 and the PRPL pattern. Is using `bundled` builds the official recommendation now or.....?
