### ISSUE TITLE
Clarification / guidance on two-way binding integration with non polymer host custom elements

### ISSUE THREAD

**Issue by bahrus** [Polymer/docs#1967]
I posed [the question on stack overflow](http://stackoverflow.com/questions/42864516/does-two-way-binding-with-polymer-2-only-work-with-polymer-elements) of whether Polymer's two way binding support can work with non Polymer host containing custom elements.  Reading the Polymer documentation on two-way binding, I put the odds at 50%, hoping the answer would be yes.  I was hoping Polymer would call the setter method of the containing custom element with the property name.

The answer I got from stack overflow confirmed my findings that the answer is no, that you need to extend Polymer.Element for this to work.  At a minimum, I think the documentation should mention that two-way binding only works between two Polymer elements.

Since multiple inheritance is not supported, the lack of two-way binding support when integrating with non Polymer elements seems to me to be an inconvenience.  I know two-way binding is viewed with suspicion these days, but I still think it is nice to be able to opt in.  Is there a way, maybe with mix-ins, to give a non polymer element the necessary clues, so that two-way binding can work?  If so, it would be nice to see that documented.

**Comment by katejeffreys** [comment]
@graynorton @sorvell would either of you be able to answer these questions?

1. Can we confirm that two-way binding only works between two Polymer elements?
2. Is there a way, maybe with mix-ins, to give a non polymer element the necessary clues, so that two-way binding can work?

**Comment by kevinpschaaf** [comment]
@bahrus @katejeffreys Polymer's data-binding is very simple to understand:
* When a Polymer host element's property changes and it is bound to a child element in its template via the `{{...}}` syntax, the `setter` for the host property runs code that _simply sets the changed property value to the child_
* When a child element's property changes, Polymer listens for an _event indicating the property changed_; when the event is caught, it reads the property from the child and sets the value to the host.

It is less of a "system" as much as it is a "pattern".  Neither the host nor the child need to be a Polymer element as long as they follow the pattern/convention.

https://github.com/bahrus/xtal/blob/master/tests/fetch-container.js#L8 certainly won't work since `FetchContainer` is not a Polymer element that would parse the `{{...}}` syntax and set up a `setter` on `FetchContainer` to set the `generatedJSON` value to the child (and also, in Polymer `{{...}}` binding syntax can currently only be specified in the element's `<template>`, not via `innerHTML`).

However, `FetchContainer` could simply follow the _pattern_ without extending `Polymer.Element` or mixing in `Polymer.PropertyEffects` (which provides bound template stamping capabilities):
* In `connectedCallback`, after creating the `<xtal-fetch>`, add an event listener that listens for a change event and sets the child value back to the host, i.e.:
   ```
   connectedCallback() {
     ...
     this.querySelector('xtal-fetch')
       .addEventListener('result-changed', e => this.generatedJSON = e.target.result);
   }
   ```
* If you actually want changes in `FetchElement`'s `generatedJSON` value to also propagate to the `<xtal-fetch>.result` if it changes in the host (seems like you probably don't, but just in case since this is actually what 2-way binding does), the `generatedJSON` setter can set the value to the `<xtal-fetch>` element as well
   ```
   set generatedJSON(val) {
     ...
     this.querySelector('xtal-fetch').result = val;
   }
   ```

Hope that helps.

**Comment by kevinpschaaf** [comment]
Also, I'll also just point out that multiple inheritance is effectively supported via class expression mixin functions, and Polymer 2 vends all of its useful features as mixins that can be added to any existing custom element class definition.  So that's another avenue you could explore.  For example, you can simply do `class FetchElement extends Polymer.ElementMixin(HTMLElement)` in your example to get all the goodies of a Polymer element.  Your whether you want to do the more raw approach above, or just imbue your custom element with Polymer features.

**Comment by bahrus** [comment]
I appreciate the helpful comments.

I'm sure I'm not articulating myself clearly, because these terms like "two-way binding" appear to me to take on slightly different meanings depending on context.

The beauty of Polymer's two-way binding, is that the container element doesn't have to be aware (from the developer's point of view) of what it's children are saying to each other.  No need for lines like this:

```JavaScript
this.querySelector('xtal-fetch')
    .addEventListener('result-changed', e => this.generatedJSON = e.target.result);
```
It acts, to the non-polymer expert, like a kind of reflective sounding board, so that children can broadcast a changed property, which the host element appears to reflect back down to sibling elements that want to know about that changed property.

In fact, I did explore what it takes to achieve this delightful effect on my own.  The code can be found [here](url).  It basically programmatically searches all the children for custom elements that have the telltale Polymer signature -- a static properties getter.  It iterates through all those properties, looking for  properties set to "notify".  It programmatically adds listeners for these property change events, using code like you provided above, and then searches for children that have properties bound to that changed property name.  I suspect, though, I'm missing some nuances of what Polymer does (like if new elements are added, etc).  I wouldn't be surprised if there's a simpler way to do it. 

**That's** what I was really hoping to see documented, or a mix-in provided (maybe there's already a mix-in that does this?).

**Comment by kevinpschaaf** [comment]
Polymer goes to great pains to avoid the _instance time_ work you're describing, because that would impact performance.  Rather, the host scans its template (once, ever) looking for `{{...}}`, and generates efficient data structures used at instance time to a.) push properties down to children on changes, and b.) add listeners that do the reverse on child property changes.  

2-way binding in Polymer always propagates data through a host property, never directly between children (via the [mediator](https://www.polymer-project.org/1.0/docs/devguide/data-system#data-flow) [pattern](https://www.youtube.com/watch?v=ZDjiUmx51y8)).  So a host sets up these bindings without knowledge or care as to whether the children are Polymer elements or not; the only thing the host requires is that the child a.) accept a property change, and b.) fire an event when the child property changes (by convention the event expected is `<property>-changed`, but can be customized via the `{{property::event}}` syntax.

I don't know what else beyond [this section](https://www.polymer-project.org/1.0/docs/devguide/data-system#upward-and-downward-data-flow) we would document to explain how it works, and again if you'd like to implement this 2-way binding pattern in your host element you can just apply the `Polymer.ElementMixin` mixin to your element and get these features rather than implementing them yourself.

**Comment by bahrus** [comment]
Thanks for the clarification.  I'm not surprised that what I did is not optimized, but it's good to get that confirmed.  I also didn't read your message carefully enough regarding mixins.

I will try your Element.Mixin suggestion -- I didn't catch that that would cause two-way binding to work, apologies for that.  

But  my suspicion, looking at the code now, is that Element.Mixin might be _too_ powerful.  The reason I was avoiding using Polymer.Element in the first place, which I should have explained, is that I wanted to create a "Polymer Lite" which would allow me to opt out of Shadow DOM, while bringing in the bare essentials of Polymer that I needed.  Looking at the code, since Polymer.Element seems to just equal Element.Mixin, that might not achieve what I wanted.  Element.Mixin seems to consist of a composition of smaller mixins, which together provide all the functionality of Polymer.Element.   So I think what I was (am) looking for is the **smallest,  specific mixin** that would just provide the two-way binding support and nothing else.

I've since learned that there is another issue in the [Polymer repo](https://github.com/Polymer/polymer/issues/4473), which ebidel opened, to give users the ability to opt out of Shadow DOM.  I experimented with the suggestions there, to my satisfaction.  So everything I've been doing will probably prove moot, but I think it made me understand (and appreciate!) Polymer a little more going through the exercise.

The documentation you point to is excellent.  My only suggestion, combined with your other documentation on two-way binding, where native elements is discussed (like <input>, but I was thinking non-Polymer host elements as well), is to spell out, somewhere,  that the host element needs to be a **Polymer** host element, or one that leverages so-and-so mixin from Polymer.   I thought maybe a Polymer target element would search for its host element and just set the property.  Look at this diagram:  https://www.polymer-project.org/images/1.0/data-system/data-flow-up-new.png It wasn't obvious to me that that wouldn't be the case.  Hence I put a setter in my home-grown "Polymer Lite" host element, naiively thinking it would just magically be called, and when it didn't, I thought I might not be the only one to trip over this, hence the reason I raised this issue.

**Comment by kevinpschaaf** [comment]
👍  No worries, good feedback.

Glad you found the `_attachDom` override for opting out of Shadow DOM.

FWIW, [`Polymer.PropertyEffects`](https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.PropertyEffects) is the minimum mixin that you'd need to implement Polymer's data binding, and would just require some imperative setup that `Polymer.ElementMixin` does based on declarative info from the static getters.  Still might do more than you want though... factoring is hard. 😄
