### ISSUE TITLE
Update install 2.0 guide

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2011]
Notes from meeting (many of these comments may end up being resolved in the new build doc rather than the existing install doc):

-   replace mention of webcomponents-es5-loader.js with custom-elements-es5-adapter.js [[or whatever we end up calling it.]]
-   mention that build --js-compile injects the adapter
-   Separate the “multiple builds” copy into a new section/sub-section
-   Move "Building for deployment" out of "Install" document (into the new Build section.)
-   Both sections need to say to `npm install -g bower`
-   Add intro, something like:

    -   Polymer is distributed via the Bower package manager (link). You can install it directly via 
         Bower to start a project from scratch, or use the Polymer CLI to create a starting point 
         automatically.

**Comment by katejeffreys** [comment]
**many of these comments may end up being resolved in the new build doc rather than the existing install doc**

- [ ] replace mention of webcomponents-es5-loader.js with custom-elements-es5-adapter.js [[or whatever we end up calling it.]]

- [ ] mention that build --js-compile injects the adapter

- [ ] Separate the “multiple builds” copy into a new section/sub-section

- [ ] Move "Building for deployment" out of "Install" document (into the new Build section.)

- [ ] Both sections need to say to npm install -g bower

- [ ] Add intro, something like: Polymer is distributed via the Bower package manager (link). You can install it directly via Bower to start a project from scratch, or use the Polymer CLI to create a starting point automatically.

**Comment by katejeffreys** [comment]
**For new build doc rather than the existing install doc**

- [ ] replace mention of webcomponents-es5-loader.js with custom-elements-es5-adapter.js [[or whatever we end up calling it.]]

- [ ] mention that build --js-compile injects the adapter

- [ ] Separate the “multiple builds” copy into a new section/sub-section

- [ ] Move "Building for deployment" out of "Install" document (into the new Build section.)

**Comment by katejeffreys** [comment]
Reminder to self: https://github.com/Polymer/docs/issues/1805
