### ISSUE TITLE
Update documentation for local serving

### ISSUE THREAD

**Issue by stramel** [Polymer/docs#2237]
I am having troubles building locally, the documentation is out of date.

**Comment by katejeffreys** [comment]
Thanks! Handling this in https://github.com/PolymerElements/polymer-starter-kit/issues/1034

**Comment by stramel** [comment]
@katejeffreys I was referring to building locally for this repository. I can't get it to spin up properly to check my changes for documentation.

**Comment by katejeffreys** [comment]
Oh I see. Can you provide more info on what's going wrong?

**Comment by stramel** [comment]
I can't serve the docs locally. I have tried `sudo chmod +x server.py && ./server.py` but that doesn't work because of missing python dependencies. 

I have tried using `gulp watch` which spins up browser-sync but when I got to the URLs listed the tab just spins forever and never actually loads.

I cloned using the `--recursive` and installed Google Cloud SDK and a bunch of python stuff it said to, still no luck.

**Comment by katejeffreys** [comment]
I am confused as to which steps of the README are out of date.

Can you give some info on your environment? I am assuming you have all the prerequisites listed in the README (Python 2.7, Google Cloud SDK, App Engine Python standard environment) - maybe there is another pre-requisite we have forgotten about...

Also, which commands run successfully before you experience errors? From the README, here are the commands, in order (excluding installing dependencies), that you'd need to run in order to build the site with changes reloading automatically in the browser:

1. git clone https://github.com/Polymer/docs --recursive
2. cd docs
3. npm install 
4. gulp
5. dev_appserver.py dist/
6. gulp watch --reload

This works for me. Can you state which command will not run for you, and any errors you get?

**Comment by stramel** [comment]
I am running Linux (a stripped down Debian variant). I followed install steps to install the google-cloud-sdk and app-engine-python using v2.7(i believe, will verify in a few hours).

Followed the steps to run but `dev_appserver.py` didn't exist. So I assumed it was supposed to be `server.py` that's when it started erroring because of missing dependencies. I can't remember what all it was missing but I do remember, `jinja2`.

**Comment by katejeffreys** [comment]
I see! Does this help at all? :/ I don't know Linux very well. https://stackoverflow.com/questions/19877869/dev-appserver-py-command-not-found

**Comment by stramel** [comment]
I will check in a bit. Thanks @katejeffreys

**Comment by stramel** [comment]
Oh, I misunderstood. I didn't realize that `dev_appserver.py` was something that was available from stuff installed. I have it available, sorry!

**Comment by katejeffreys** [comment]
Glad it is fixed!
