### ISSUE TITLE
Open a new repositorie for translate polymer in to Chinese version

### ISSUE THREAD

**Issue by spyhole** [Polymer/docs#2249]
https://github.com/Polymer/docs_zh for Chinese version, let's translate it into Chinese version.
@arthurevans @notwaldorf

**Comment by wmginsberg** [comment]
Hey! Thanks for raising this issue - it has come up a few times. Unfortunately we do not currently have the bandwidth (funds or staffing) to pull this project off effectively. We also do not have anyone on the team who is capable of reviewing changes, since none of us speaks fluent Chinese, so we cannot endorse the project from our domain :( 

We would, however, be supportive of any community member creating content in their native language to share with others. We have seen great stuff in Spanish, German, and French!
