### ISSUE TITLE
Upgrade Tool

### ISSUE THREAD

**Issue by dcmcshan** [Polymer/docs#2274]
> The Polymer team plans to release a Polymer Upgrade tool to automatically perform a number of the changes required to upgrade 1.x elements to either hybrid or class-based style. The remaining changes require either manual code changes, testing, or both to ensure that your element operates the same in 2.0 as it did in 1.x. **The upgrade tool is not available at this time.**

Any ETA on when this tool will be made available?

**Comment by web-padawan** [comment]
See [this issue](https://github.com/Polymer/polymer-upgrade/issues/11#issuecomment-287217491).

BTW, from my own experience, using `polyup` to upgrade fro, 0.5 to 1.x used to introduce so much mess that I switched to manually rewriting each line of code. Since I was a newcomer then, this approach also helped me to better understand both product functionality and implementation details.
